### ISSUE TITLE
Question about sweep.py

### ISSUE THREAD

**Issue by kiranchari** [YyzHarry/SubpopBench#4]
Based on the README, the command to launch a sweep after fixing hparam with different seeds (with unknown attributes) is 

```
python -m subpopbench.sweep launch \
       --algorithms <...> \
       --dataset <...> \
       --train_attr no \
       --best_hp \
       --input_folder <...> \
       --n_trials <num_of_trials>

```

May I know how the best hparam is chosen in this step? Is it using **ValWorstAccAttributeYes** as shown in the script below? Should we modify the selection_method in this script based on our experimental setup (ValWorstAccAttributeYes vs ValWorstAccAttributeNo)?

https://github.com/YyzHarry/SubpopBench/blob/4d3dbbe21029666ef19d040e110ec22908640c5b/subpopbench/sweep.py#L81

Thanks

**Comment by YyzHarry** [comment]
Hi! Sorry for the late reply. During the training step, you shouldn't modify this line (so that the training records everything); instead, when you [collect & evaluate the final results](https://github.com/YyzHarry/SubpopBench/tree/4d3dbbe21029666ef19d040e110ec22908640c5b#collect-the-results-of-your-sweep), you choose which selection method you use:
https://github.com/YyzHarry/SubpopBench/blob/4d3dbbe21029666ef19d040e110ec22908640c5b/subpopbench/scripts/collect_results.py#L177-L181
